/*
SPDX-FileCopyrightText: 2024SAP SE or an SAP affiliate company and redis-operator contributors
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// RedisListerExpansion allows custom methods to be added to
// RedisLister.
type RedisListerExpansion interface{}

// RedisNamespaceListerExpansion allows custom methods to be added to
// RedisNamespaceLister.
type RedisNamespaceListerExpansion interface{}
