/*
SPDX-FileCopyrightText: 2023 SAP SE or an SAP affiliate company and redis-operator contributors
SPDX-License-Identifier: Apache-2.0
*/

// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

import (
	v1alpha1 "github.com/sap/redis-operator/api/v1alpha1"
	"k8s.io/apimachinery/pkg/labels"
	"k8s.io/client-go/listers"
	"k8s.io/client-go/tools/cache"
)

// RedisLister helps list Redis.
// All objects returned here must be treated as read-only.
type RedisLister interface {
	// List lists all Redis in the indexer.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.Redis, err error)
	// Redis returns an object that can list and get Redis.
	Redis(namespace string) RedisNamespaceLister
	RedisListerExpansion
}

// redisLister implements the RedisLister interface.
type redisLister struct {
	listers.ResourceIndexer[*v1alpha1.Redis]
}

// NewRedisLister returns a new RedisLister.
func NewRedisLister(indexer cache.Indexer) RedisLister {
	return &redisLister{listers.New[*v1alpha1.Redis](indexer, v1alpha1.Resource("redis"))}
}

// Redis returns an object that can list and get Redis.
func (s *redisLister) Redis(namespace string) RedisNamespaceLister {
	return redisNamespaceLister{listers.NewNamespaced[*v1alpha1.Redis](s.ResourceIndexer, namespace)}
}

// RedisNamespaceLister helps list and get Redis.
// All objects returned here must be treated as read-only.
type RedisNamespaceLister interface {
	// List lists all Redis in the indexer for a given namespace.
	// Objects returned here must be treated as read-only.
	List(selector labels.Selector) (ret []*v1alpha1.Redis, err error)
	// Get retrieves the Redis from the indexer for a given namespace and name.
	// Objects returned here must be treated as read-only.
	Get(name string) (*v1alpha1.Redis, error)
	RedisNamespaceListerExpansion
}

// redisNamespaceLister implements the RedisNamespaceLister
// interface.
type redisNamespaceLister struct {
	listers.ResourceIndexer[*v1alpha1.Redis]
}
